### ISSUE TITLE
Neutron Standard

### ISSUE THREAD

**Issue by szepeviktor** [infinum/wp-boilerplate#159]
Please consider following https://github.com/Automattic/phpcs-neutron-ruleset
WPCS is very PHP5-centric.

**Comment by dingo-d** [comment]
We're using our own standards: https://packagist.org/packages/infinum/coding-standards-wp

I was starting to work in the PSR-4 ruleset, but since PSR-12 is out, I'll probably rework them to follow modified PSR-12 + WPCS standards 🙂 

I looked at neutron standards and they have some interesting rulesets that can be ignored. It's on my radar 😄
