### ISSUE TITLE
Class 'Inf_Theme\Includes\Main'

### ISSUE THREAD

**Issue by KeironLowe92** [infinum/wp-boilerplate#59]
Just trying this out for the first time, and I'm getting the following PHP error
`Fatal error: Uncaught Error: Class 'Inf_Theme\Includes\Main' not found in /Users/keironlowe/Development/infin_test/wp-content/themes/infin_test/functions.php`

I did have a few issues when running _rename.sh, mainly `sed: RE error: illegal byte sequence`, could it be related?

**Comment by dingo-d** [comment]
Yes, we're aware of the issue, I'll create a PR to fix the issue when running a rename script. The namespace isn't being replaced properly.

The sed error comes if you are using a diacritic, or 'non-pure' Latin name in the description (author name or one of the replace items). It replaces them so that error can be ignored.

We will move to node script for replacing soon.

In the meantime, you can manually search and replace `Inf_Theme` with the capitalized name of your theme (and replace - with _).

**Comment by dingo-d** [comment]
@KeironLowe92 We updated a lot in the `development` branch and the rename script should be working.

The sed issue is due to mac OS, and it's safe to ignore.

If you want to you can check it out and let us know if there is anything to fix/add.

**Comment by dingo-d** [comment]
With the new rename script, this should be solved completely. Let us know if any issue pops out :)
