### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by dingo-d** [infinum/wp-boilerplate#65]
Once contributing, issue template and travis integration are merged, Readme should be updated to point to the templates and how to contribute. Also we should add some additional badges to showcase some interesting stats about the project (build, version, download count, etc.) using https://shields.io/, like I've added on the [json-wp-post-parser](https://github.com/infinum/json-wp-post-parser).

**Comment by iruzevic** [comment]
Rename script is switched to node version.

**Thing to do:**

Better color coding (test on white terminal just in case) - separate beginning statement (Theme name:), and end statement (My theme name)
  Progress bar instead of the list of renamed files
  Options to debug the renaming script in the event something isn't working (show full output or something alike)
  Ability to already rename the theme once it's already renamed. This could be tricky because you'll need to know all the specific strings you've replaced them in the first place. Maybe all the initial replacement details could be written in some .json file so that it can be pulled from there for the future replacement

**Comment by iruzevic** [comment]
We should test this before merging version 3

**Comment by iruzevic** [comment]
I have updated the readme to work in new setup. 

We have 3 problems. Rename.js is not renaming 2 files:
.eslint

- ignore
- .gitignore

please fix this after we merge #84 to development branch.

**Comment by dingo-d** [comment]
Will do, I also had a thought as to how we could (possibly) fix the multiple renaming with that script - upon running the rename script, a `rename-{themename}.json` could be created that would act as a sort of manifest from which we could then read the existing naming and replace the new one - this would make the rename reusable.

**Comment by iruzevic** [comment]
great idea but this will only complicate boilerplate even more. lets close this ticket and i will open another one for the rename script
